# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#  1. find Fibonacci sequence out to four million
fib <- c(1, 2, 3)
n <- length(fib)
while(fib[n] < 4000000){
	fib <- c(fib, sum(fib[n], fib[n-1]))
	n <- length(fib)
}
sum(fib[fib %% 2 == 0])
	